### ISSUE TITLE
Entering a hex value without the hash as the first character will replace the first character with a 0

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#10]
**The Bug**
Entering a hex value without the hash as the first character will replace the first character with a 0. As a result the colour is changed to an incorrect colour.

**To Reproduce**
1. Claim a square with a hex value but exclude the "#"

**Comment by emilioziniades** [comment]
Great, latest commit has addressed this bug. I tested both with and without '#'

**Comment by gshorer97** [comment]
Im still getting this bug on my end... Im not too sure why

**Comment by emilioziniades** [comment]
Yeah, my bad. I fixed it for manageForm, but not for mintForm. I have made new commits and its gone on my side, closing this issue for now... reopen if it persists
