### ISSUE TITLE
Remove square borders on canvas by default

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#13]
Remove the 1px black border around each square.
I suggest keeping a small border around the entire canvas to separate the element from the web background.

Rationale:
Finalised pixel art would generically not show the canvas grid

**Comment by emilioziniades** [comment]
Totally agree, looks way better without borders. Latest commit has corrected that (also worth noting: the way the hosting is set up, it triggers a deploy to the site every time this repo is updated)
