### ISSUE TITLE
Align the Manage your Squares section to a table

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#16]
Currently: Each list item in the "Manage Squares" section is not aligned to neighboring items.
At the moment this is not much of an issue and the alignments are only slightly off from each other. However, I can imagine this becoming worse when we add the ability to change the square names.

Instead: Align each element in the row to a column in a table

**Comment by emilioziniades** [comment]
Before, the rows were laid out using flexbox centered vertically. I have now represented the squares within an html table, so they should remain perfectly centered.
