### ISSUE TITLE
Select and Hover states for squares on the canvas

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#18]
A user should be able to select any square within the canvas to view its details. This will reflect information about that square (this has been detailed in a separate ticket)

Suggested behaviors:
> Hover state:
- Display a border for the column and row that the square belongs to (essentially displaying a target)

> Selected state:
- Display border for just that square

**Comment by gshorer97** [comment]
User should only be able to select one square at a time

**Comment by emilioziniades** [comment]
Love it - gonna get started today on this

**Comment by gshorer97** [comment]
I'm looking into a function to invert hex colours so that the border rendered will be the inverted colour of the square.
This might not be needed but I'm thinking for cases when the border is barely noticeable like if the sqaure itself is black or dark grey.

**Comment by gshorer97** [comment]
Also can use the numberToCoords function to determine which row and col to highlight

**Comment by emilioziniades** [comment]
@gshorer97 inverting the hex colour of the border is genius. Definitely look into that. 

I have implemented selected state and hover state in Commit 2667e25ed50ffdfaefbf2819d8911aec76dd95ca, so closing this issue and opening a new issue with regards to the border colour. Reopen if I missed something.
