### ISSUE TITLE
Add basic stats about the current flatland

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#20]
When no square is highlighted by the user we can display some basic statistics about the canvas as a whole.

Potential statistics we could include:
- Start date
- Number of collaborators (potentially list contributors by username)
- Number of owned and unowned squares
- Can determine average colour/show modal colour

(Can print this on the proposed right side-panel)

**Comment by emilioziniades** [comment]
Similar to issue #12 , I am going to break up this issue into smaller ones, and some of those will only be possible after we update the smart contract.

Key: ✅ = implemented, ❌ = not implemented, 🤝 = requires changes to the smart contract

- 🤝 Start date
- 🤝 Number of collaborators (potentially list contributors by username)
- ✅ Number of owned and unowned squares
- ❓Can determine average colour/show modal colour (_idk about this - it doesn't seem like useful information by itself. Reopen the issue if further discussion needed_)
