### ISSUE TITLE
Broadcast recent smartcontract activity to users

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#48]
When a user interacts with the smart contract we can broadcast that to other users so the flatland seems more dynamic and interactive.

Can indicate all interacts:
- [User] renamed Square
- [User] claimed Square at (x, y)

Could possibly implement this as another side panel and each event can be a toast above the last event

**Comment by gshorer97** [comment]
Since this is a relatively large addition (likely needing sub-files) I think it should be in a separate folder from the canvas folder.

Would be nice if it dynamically showed the last few transactions (~6ish) as individual toasts.
The last toast in the list could maybe be a "see all transactions" toast

**Comment by emilioziniades** [comment]
Definitely agreed. There are two things our app should listen for:

1. New square claims
2. Square colour changes

**Comment by emilioziniades** [comment]
Ok so I have made some progress on this in commit 882ef6c5517179b9abef566f260409d7e3cd56cc 

I just wanted to lay out what is left to do: 

Placement 

- [ ]  Implement tabs for 'Square Manager' and 'History'
- [ ] Show only 6 most recent events on actual canvas (in a column next to side panel), and show all in History

Content 

- [ ] Implement the same feature for Colour Change Events
- [ ] Make toasts dismissible
- [ ] Add square icon on top left of toast
- [ ] when toast is clicked, relevant square is selected in canvas above
- [ ] Indicate who square owner is in toast

**Comment by gshorer97** [comment]
Thanks for all the work so far. I have a few thoughts and comments that we could discuss going forward:

- I agree that there should be a separation between the 'Recent Activity' and 'History' tab

- The 'Recent Activity' panel
-- Shows the latest transactions 
-- # of transactions shown can be a fixed # but in future could consider scaling up and down depending on screen size
-- Can implement as a row with columns. With each update the toast of one column can shift to the next and discarding the last.

- History tab
-- I think when assessing the transaction history it would be better to process this information into a table since we are looking at many entries
-- We should limit the table length to latest 100 entries and have the option to load the rest of the entries to help with loading times
-- There could be a toggle to only show the users transactions which will then filter the table accordingly

- Side panel
-- I think we could implement another form of history on the side panel to show the history of the clicked square
-- We could have a "show square history" button on the clicked square alert 
-- Perhaps we could have the square icon clickable with a tooltip "see square history" instead
-- Could bring up a modal showing a table/toasts from that square only


- Other thoughts:
-- Is there value in providing the transaction hash? Maybe we could display it as a tooltip on hover of the toasts and as a column in the table
-- Is there value in adding a User page where all users can access and see the activity of one user?

**Comment by emilioziniades** [comment]
Hey dude, thanks for the thoughtful comments, my response below:

- Recent Activity panel
    - Yeah I think you're spot on to bring up the responsiveness on the site. Luckily, react-bootstrap handles a lot of this behind the scenes, and if you visit Flatland via the Metamask wallet/browser mobile app, it already looks pretty decent

- History Tab
    - Also agreed, the Toasts don't look great in a grid like that. A paginated table makes much more sense
    - It would be nice to show who claimed/changed squares. Unfortunately, the smart contract events only share data about 1) the square id and 2) the colour of the affect square. So we would need to update the event emitters in the smart contract
 
- Side Panel
   -  (you said these ideas are controversial but I think they're all great lol)
   - it would be awesome to see a square's history. Especially when they are transferred between users too. It could say the price it was sold for. (Check out this page for [ CryptoPunk # 1 ](https://www.larvalabs.com/cryptopunks/details/1)

- Other thoughts
    - Transaction hash would be useful - we could create it as an etherscan link so that they can view the tx themselves
    - Same for address page. The data is all publicly available on the blockchain, so we may as well represent it on our site - again, see the [example from CryptoPunks](https://www.larvalabs.com/cryptopunks/accountinfo?account=0xb88f61e6fbda83fbfffabe364112137480398018)

**Comment by emilioziniades** [comment]
It seems like the remaining tasks from this issue are now in #70 and #71, so I am going to close this issue. Please re-open if there's something I missed
