### ISSUE TITLE
Transaction confirmation alert will print a successful transaction even if the user denies the transaction

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#54]
If a user denies the transaction on the level of metamask then the alert will still appear saying that the transaction was successful.

Intended behaviour:
If there is no new transaction logged on the blockchain the alert should come back as a unsuccessful transaction

**Comment by emilioziniades** [comment]
Good catch. I've remedied this in commmit a3094ed1171feb165e8cb32da407c9df8d9479dd . It now spits out "error processing transaction" if the tx was unsuccessful. Closing this issue
