### ISSUE TITLE
Flatland doesn't recognize when account changes

### ISSUE THREAD

**Issue by emilioziniades** [emilioziniades/flatland#58]
If you switch accounts on MetaMask whilst you are logged in, the dapp doesn't recognize that the account changed.

This causes loads of problems, because there is a mismatch between the account loaded in state and the account that Metamask will use to process transactions. So you might try and change a square that doesn't belong to you ( which will revert with an error due to the Ethereum smart contract. 

There is an easy fix for this: see https://docs.metamask.io/guide/accessing-accounts.html . We create a listener function, and simply dispatch ({type: 'LOAD'} if the account changes

**Comment by gshorer97** [comment]
Great find! quite an important thing to fix

**Comment by emilioziniades** [comment]
Have addressed this in commit 431ef1f17c534fa197c387b7b699d61a1662bd0a . Closing.
