### ISSUE TITLE
ethereum.enable() is deprecated and needs to be replaced by eth_requestAccounts

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#60]
It seems the current login ethereum.enable login method is soon not going to be supported and needs to be replaced by a new function.

Console warning message:
> MetaMask: 'ethereum.enable()' is deprecated and may be removed in the future. Please use the 'eth_requestAccounts' RPC method instead.
> For more information, see: https://eips.ethereum.org/EIPS/eip-1102

**Comment by emilioziniades** [comment]
Addressed in commit ca7809bd5562cda77e75e6ee10e7e872b62cc6ca , closing issue.
