### ISSUE TITLE
Ensure Flatland state consistent across instances

### ISSUE THREAD

**Issue by emilioziniades** [emilioziniades/flatland#65]
I am currently working on updating all active instances of Flatland when a user claims/changes a square. 

And what I realized is that not only should the recent activity change, but all other elements of state must also change. Right now, the toasts will show the latest activity, but the Canvas won't 100% correspond to the recent activity displayed on the side.

So we need to use the event listeners to update state when a new event is emitted from the smart contract.

**Comment by emilioziniades** [comment]
Here's an example of the bug - I changed the colour of square 29 (from red to yellow) on one computer, and had this instance open on another computer
<img width="1440" alt="Screenshot 2021-04-26 at 22 38 08" src="https://user-images.githubusercontent.com/75438244/116147592-39f25500-a6e0-11eb-9988-baaf9548d5bf.png">

**Comment by gshorer97** [comment]
Great point! Ideally, updates happen globally and are listened to locally from the same source rather than many different local events listened locally

**Comment by emilioziniades** [comment]
Yeah totally agree. Take the example of claiming square.

Currently: user mints square, app waits for confirmation (and stores data from form submission), upon confirmation, updates local state from local form data

Should be:

user mints square, app waits for event emitter, updates local state from Ethereum blockchain state

**Comment by emilioziniades** [comment]
Have addressed this bug in commit a7c09f99acf7de4fa1f4131e2785701c64e5d796. The whole state updates correctly when a remote colour change or square claim occurs
