### ISSUE TITLE
Proposed changes to DateTime display in event toasts

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#66]
The toasts are looking great but I think we can clean up how we display the datetime here slightly

Here are some proposed changes:
- Remove the seconds from the time
- If the date matches the current date then we can just display the time and not the date

**Comment by gshorer97** [comment]
Additionally, to combat the lag time while the system computes the blockheight to datetime conversion we should rearrange the order of the toast event string such that the date prints last and then only appears when in datetime format

**Comment by gshorer97** [comment]
There's been some progress with this issue already so I'll just summarise the issue below:

- [ ] Remove seconds 
- [ ] Rearrange order of toast message
- [ ] If date matches with current date > only print time
- [ ] Prevent rendering of blockheight altogether until the blockheight to date conversion has occurred

**Comment by emilioziniades** [comment]
Have implemented this in commit ba58e3818e2abce7680c49c34f5bf93e780d2ec4 . Closing
