### ISSUE TITLE
See event history of individual square

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#71]
As per our discussion in #48: We should be able to generate the history of transactions for individual squares. 

A proposed method of bringing this to the frontend:
- Individual square data is best shown on the side panel when selected
- we can implement a button here to show the history (or we can make the square icon clickable)
- once clicked, a modal box appears with a table of all the transactions of that square

**Comment by gshorer97** [comment]
I've started on this issue in the `single-square-history` branch. Here are a few comments so far

- I am running into a similar error to the colour picker here where the modal will only stay onscreen once the date conversion has occurred
- I am using EventRow to print the table rows but in this particular table printing the square ID each time is redundant
- Should maybe consider pagination of the table

**Comment by emilioziniades** [comment]
Since commit f80af93c091da8fd44810dc931ac53c860c7ed40 , which addressed the bug in issue #88 , the single square history does not disappear with each re-render. It seems like this rendering bug happens when we nest components too deeply. Refactoring always seems to resolve it

**Comment by emilioziniades** [comment]
In commit 9d638f6fd976e692d3ff498befc623db32dcc2e5 , I added a `showID` prop to eventRow, which can be true or false, depending on whether you're using it in canvasHistory or squareHistory

So then, from your list, the only thing left to do is paginate the table. Since you have already done the pagination for canvasHistory, there should be a way to reuse the code for squareHistory too. You could have a <PaginatedTable> component, and then wrap each table inside the component.

**Comment by gshorer97** [comment]
Perfect. Thanks a lot dude. I will add the pagination. There are some complexities to the pagination which make it hard to isolate into its own component since it is quite dependent on receiving and providing information (onClick events, updating states, page numbers, etc.) to the original component. I will look into this a bit more though. It would be nice to tidy up the code further. 

I also want to add a query for the edge case that the index square is not involved in any transactions. If so, then rather print a short text in the modal component instead of the blank table
