### ISSUE TITLE
Change colour button should be disabled until a colour is selected

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#81]
Currently, the user can click any change colour button before choosing a colour. These buttons should rather be disabled until the user has made a change with the colour picker.

**Comment by emilioziniades** [comment]
Yeah dude, good catch. Addressed this in commit b51f5e099e6190ed732bc200865af3d35bbce920

I have updated the submit button in baseForm. It is now disabled when the input is empty, and also when that form is loading.

Closing.
