### ISSUE TITLE
Add transaction hash to history table

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#85]
Transaction hash should be added to the History table.

Implementation:
- Rightmost column
- Hash strings should be sliced to n length with '...' appended 
- On hover: Tooltip with full transaction hash as link to see full transaction details

**Comment by emilioziniades** [comment]
Have implemented this in commit c61a2eaf30670994e3b3c388f01b35defa59a61f . Closing

**Comment by gshorer97** [comment]
Looking great
