### ISSUE TITLE
colour picker in sidePanel buggy until date replacement completed

### ISSUE THREAD

**Issue by emilioziniades** [emilioziniades/flatland#88]
If you try and open the colour picker in sidePanel, it will close immediately.

What is confusing though is that this does not occur in squareManager, which suggests to me that the issue is in sidePanel

**Comment by emilioziniades** [comment]
After some fiddling, I realize that the issue is the date replacement function. It is only whilst the date replacement is occuring that the picker does not remain open. This is only an issue since commit 116bd9b254a1b25284afdce623987b5db06aef04 , where I split up the date replacement state updates into lots of little state updates instead of one big one, so that new events would not be overridden in that initial loading period.

I think I know what's going on here: When the date replacement is occuring, it is continuously updating `blockchainState`. `canvas` is reading `history` from `blockchainState`, and taking the six most recent events.

 In react, state updates cause re-renders. Every time a date replacement occurs, state is updated, and  `canvas` is re-rendered. Colour picker initially renders with `pickerVisible = false`. So basically the `canvas` component is stuck in a re-rendering loop. I think the best bet would be to split up the state between `canvas` and `sidePanel`, so that updates to `history` do not cause `canvas` to re-render

**Comment by gshorer97** [comment]
Great find. I agree with your findings and conclusion. We can try render the recent events in app.js in the same row as the canvas instead.

**Comment by emilioziniades** [comment]
Yeah this is a good idea, I'll give it a bash now

**Comment by emilioziniades** [comment]
This bug is fixed as of f80af93c091da8fd44810dc931ac53c860c7ed40 . Instead of showing `recentEvents` in `app` , I split up `canvas` and `recentEvents` are now rendered from `canvasLayout`. Closing this issue, re-open if the bug persists
