### ISSUE TITLE
Log transaction hash and link to etherscan upon successful mint/ colour change (in a popup under relevant button)

### ISSUE THREAD

**Issue by emilioziniades** [emilioziniades/flatland#9]
Currently, the app indicates that it is awaiting confirmation. But once confirmation occurs, it does not indicate the successful confirmation. 

Instead, it should log the confirmed transaction, and provide a link to etherscan so that users may inspect the transaction.

**Comment by gshorer97** [comment]
This is a great idea. I think a much needed feature. We could possibly implement this with [Modals](https://react-bootstrap.github.io/components/modal/)

**Comment by gshorer97** [comment]
or perhaps [Toasts](https://react-bootstrap.github.io/components/toasts/)

**Comment by emilioziniades** [comment]
Have made some progress in commit ea360382e2a790ad5cc7e44176a6fc17cd30c15b

Went for the Alert component because of its show and dismissible prop. But if you wanted to change it to either Modals or Toasts, that would also be cool.

Keeping this issue open, because currently the notifications work perfectly for SquareManager (both claim and colour change), but not on the SidePanel. This is weird to me because both are reusing the same forms. But will look into it tomorrow.

**Comment by emilioziniades** [comment]
Resolved in commit 116bd9b254a1b25284afdce623987b5db06aef04 . Now confirmation / error message shown in a snackbar at the bottom of the screen. Closing this issue.
