### ISSUE TITLE
Default canvas history page to 1 when changing between all and user transactions

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#92]
When the toggle history button is pressed the table should default to the first page of whatever table is requested.

This is a super easy addition:
- `onChange` of the toggle should simply also include `setCurrentPage(1)`

**Comment by emilioziniades** [comment]
This was addressed by @gshorer97 in 1b6bacd3e91379e30fad2bd75a27210a819b59c8 . Closing
