### ISSUE TITLE
Compute blockHeightToDate only if event is visible

### ISSUE THREAD

**Issue by emilioziniades** [emilioziniades/flatland#96]
Currently, the app goes once through and computes all the dates from block heights. Each individual check is quick, but this adds up when the number of logs is large.

Rather, we should only compute the date as needed.

- First six 'recent' event toasts will always be computed on startup
- Date for first page of events only computed when user switches to that tab
- Each subsequent page of events will only calculate the date if a user has clicked onto that page

**Comment by gshorer97** [comment]
Additionally, the function should only run once for each entry

**Comment by gshorer97** [comment]
Changes to blockheight to date conversion in 49f794a7ecb6f7333b32fa44becc9ea38f6fb392 

- Blockheight to date conversion for all transactions is no longer performed on runtime.
- Instead any on-screen transaction (manage tab, square history, recent events) will run a batchEventBlockHeightToDate function with all the relevant events
- batchEventBlockHeightToDate is found within the blockchainUtils file
- Events which have already had their dates calculated will be ignored by the function to further optimise the code

Recent Events dates only load with a component update - I am struggling to find a way to automatically update it. For Manage squares table and square history table I am using useEffect and useState which causes the components to re-render with the dates. This solution doesn't seem to be working with Recent Events. I will close this issue and open another one with this specific problem to look into in the future.
